version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    environment:
      - API_KEY=${API_KEY}
    networks:
      - weather-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge